-- 001: Extensions and global ENUM types used across many modules
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE user_role AS ENUM ('OWNER', 'MANAGER', 'SUPERVISOR', 'WORKER', 'ACCOUNTANT');
CREATE TYPE employment_status AS ENUM ('ACTIVE', 'ON_LEAVE', 'TERMINATED', 'SUSPENDED');
CREATE TYPE attendance_status AS ENUM ('PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE', 'HOLIDAY');
CREATE TYPE leave_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE leave_type AS ENUM ('SICK', 'CASUAL', 'EARNED', 'UNPAID', 'MATERNITY', 'PATERNITY');
CREATE TYPE payroll_status AS ENUM ('DRAFT', 'GENERATED', 'PAID', 'CANCELLED');
CREATE TYPE machine_status AS ENUM ('RUNNING', 'IDLE', 'BREAKDOWN', 'MAINTENANCE', 'OFFLINE');
CREATE TYPE machine_log_event AS ENUM ('START', 'STOP', 'BREAKDOWN', 'MAINTENANCE', 'IDLE');
CREATE TYPE breakdown_status AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED');
CREATE TYPE maintenance_type AS ENUM ('PREVENTIVE', 'CORRECTIVE', 'PREDICTIVE');
CREATE TYPE maintenance_status AS ENUM ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');
CREATE TYPE beam_status AS ENUM ('IN_STOCK', 'ALLOCATED', 'IN_USE', 'EMPTY', 'DAMAGED');
CREATE TYPE work_order_status AS ENUM ('DRAFT', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD');
CREATE TYPE production_order_status AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD');
CREATE TYPE roll_status AS ENUM ('PRODUCED', 'IN_QC', 'QC_PASSED', 'QC_FAILED', 'PACKED', 'DISPATCHED');
CREATE TYPE inventory_txn_type AS ENUM ('IN', 'OUT', 'ADJUSTMENT', 'TRANSFER', 'RETURN');
CREATE TYPE po_status AS ENUM ('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED');
CREATE TYPE so_status AS ENUM ('DRAFT', 'CONFIRMED', 'IN_PRODUCTION', 'READY', 'PARTIALLY_DISPATCHED', 'DISPATCHED', 'CANCELLED');
CREATE TYPE qc_result AS ENUM ('PENDING', 'PASS', 'FAIL', 'REWORK');
CREATE TYPE packing_status AS ENUM ('PENDING', 'PACKED', 'DISPATCHED');
CREATE TYPE dispatch_status AS ENUM ('PENDING', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED');
CREATE TYPE vehicle_status AS ENUM ('AVAILABLE', 'ON_TRIP', 'MAINTENANCE', 'OUT_OF_SERVICE');
CREATE TYPE expense_category AS ENUM ('RAW_MATERIAL', 'UTILITY', 'SALARY', 'MAINTENANCE', 'TRANSPORT', 'ADMIN', 'OTHER');
CREATE TYPE notification_severity AS ENUM ('INFO', 'WARNING', 'CRITICAL');
CREATE TYPE waste_type AS ENUM ('YARN_WASTE', 'FABRIC_WASTE', 'PROCESS_WASTE', 'OTHER');
